services:
  easyconnect:
    image: ${IMAGE:-hagb/docker-easyconnect:latest}
    container_name: easyconnect
    network_mode: host
    restart: "no"
    stop_grace_period: 5s
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - QT_QPA_PLATFORM=xcb
      - EXIT=1
      - CLIP_TEXT=${CLIP_TEXT}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${DATA_DIR:-~/.easyconnect-data}:/root/conf

  easyconnect-cli:
    image: ${IMAGE_CLI:-hagb/docker-easyconnect:cli}
    container_name: easyconnect
    network_mode: host
    restart: "no"
    stop_grace_period: 5s
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    environment:
      - EXIT=1
      - CLI_OPTS=-d ${SVPN_HOST} -u ${VPN_USER} -p ${VPN_PASS}
    volumes:
      - ${DATA_DIR:-~/.easyconnect-data}:/root/conf
    profiles:
      - cli
